// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/add-post": {
            "post": {
                "description": "Add a new post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PostsService"
                ],
                "summary": "Add post",
                "parameters": [
                    {
                        "description": "Add Post Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PostResponse"
                        }
                    }
                }
            }
        },
        "/api/add-telegram": {
            "post": {
                "description": "Add a new telegram",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Buffer"
                ],
                "summary": "Add telegram",
                "parameters": [
                    {
                        "description": "Add Telegram Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddTelegramRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AddTelegramResponse"
                        }
                    }
                }
            }
        },
        "/api/delete-post": {
            "delete": {
                "description": "Delete the post by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PostsService"
                ],
                "summary": "Delete the post",
                "parameters": [
                    {
                        "description": "Delete Post Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeletePostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PostResponse"
                        }
                    }
                }
            }
        },
        "/api/find-posts": {
            "get": {
                "description": "Find posts by serchstring",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PostsService"
                ],
                "summary": "Find posts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search Substring",
                        "name": "substring",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PostsResponse"
                        }
                    }
                }
            }
        },
        "/api/get-all-posts": {
            "get": {
                "description": "Get all posts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PostsService"
                ],
                "summary": "Get all posts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PostsResponse"
                        }
                    }
                }
            }
        },
        "/api/get-post": {
            "get": {
                "description": "Get the post by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PostsService"
                ],
                "summary": "Get the post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Post ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PostResponse"
                        }
                    }
                }
            }
        },
        "/api/get-posts": {
            "get": {
                "description": "Get posts by page",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PostsService"
                ],
                "summary": "Gets posts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page_number",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetPostsPageResponse"
                        }
                    }
                }
            }
        },
        "/api/update-post": {
            "put": {
                "description": "Update the post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PostsService"
                ],
                "summary": "Update the post",
                "parameters": [
                    {
                        "description": "Update Post Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PostResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AddTelegramRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "dto.AddTelegramResponse": {
            "type": "object",
            "properties": {
                "telegrams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Telegram"
                    }
                }
            }
        },
        "dto.DeletePostRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "dto.GetPostsPageResponse": {
            "type": "object",
            "properties": {
                "max_page_number": {
                    "type": "integer"
                },
                "page_number": {
                    "type": "integer"
                },
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Post"
                    }
                }
            }
        },
        "dto.IcePhenomenia": {
            "type": "object",
            "properties": {
                "intensity": {
                    "type": "integer"
                },
                "phenomen": {
                    "type": "integer"
                }
            }
        },
        "dto.Post": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "river": {
                    "type": "string"
                }
            }
        },
        "dto.PostRequest": {
            "type": "object",
            "properties": {
                "post": {
                    "$ref": "#/definitions/dto.Post"
                }
            }
        },
        "dto.PostResponse": {
            "type": "object",
            "properties": {
                "post": {
                    "$ref": "#/definitions/dto.Post"
                }
            }
        },
        "dto.PostsResponse": {
            "type": "object",
            "properties": {
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Post"
                    }
                }
            }
        },
        "dto.Telegram": {
            "type": "object",
            "properties": {
                "air_temperature": {
                    "type": "integer"
                },
                "average_reservoir_level": {
                    "type": "integer"
                },
                "datetime": {
                    "type": "string"
                },
                "delta_water_level": {
                    "type": "integer"
                },
                "downstream_level": {
                    "type": "integer"
                },
                "group_id": {
                    "type": "string"
                },
                "headwater_level": {
                    "type": "integer"
                },
                "ice_height": {
                    "type": "integer"
                },
                "ice_phenomenia_state": {
                    "type": "integer"
                },
                "ice_phenomenias": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.IcePhenomenia"
                    }
                },
                "id": {
                    "type": "string"
                },
                "inflow": {
                    "type": "number"
                },
                "is_dangerous": {
                    "type": "boolean"
                },
                "post_code": {
                    "type": "string"
                },
                "precipitation_duration": {
                    "type": "integer"
                },
                "precipitation_value": {
                    "type": "number"
                },
                "reservoir_date": {
                    "type": "string"
                },
                "reservoir_volume": {
                    "type": "number"
                },
                "reservoir_water_inflow_date": {
                    "type": "string"
                },
                "reset": {
                    "type": "number"
                },
                "snow_height": {
                    "type": "integer"
                },
                "telegram_code": {
                    "type": "string"
                },
                "water_flow": {
                    "type": "number"
                },
                "water_level_on20h": {
                    "type": "integer"
                },
                "water_level_on_time": {
                    "type": "integer"
                },
                "water_temperature": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "HLGateway API",
	Description:      "This is the HLGateway server API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
