basePath: /api/v1
definitions:
  dto.AddControlValueRequest:
    properties:
      date_start:
        type: string
      post_code:
        type: string
      type:
        $ref: '#/definitions/dto.ControlValueType'
      value:
        type: integer
    type: object
  dto.AddControlValueResponse:
    properties:
      control_value:
        $ref: '#/definitions/dto.ControlValue'
    type: object
  dto.AddTelegramRequest:
    properties:
      code:
        type: string
    type: object
  dto.AddTelegramResponse:
    properties:
      telegrams:
        items:
          $ref: '#/definitions/dto.Telegram'
        type: array
    type: object
  dto.CheckWaterLevelResponse:
    properties:
      excess:
        type: integer
    type: object
  dto.ControlValue:
    properties:
      date_start:
        type: string
      id:
        type: string
      post_code:
        type: string
      type:
        $ref: '#/definitions/dto.ControlValueType'
      value:
        type: integer
    type: object
  dto.ControlValueType:
    enum:
    - 0
    - 1
    - 2
    - 3
    - 4
    type: integer
    x-enum-varnames:
    - None
    - Norm
    - Floodplain
    - Adverse
    - Dangerous
  dto.DeletePostRequest:
    properties:
      id:
        type: string
    type: object
  dto.GetControlValuesResponse:
    properties:
      control_values:
        items:
          $ref: '#/definitions/dto.ControlValue'
        type: array
      max_page:
        type: integer
      page:
        type: integer
    type: object
  dto.GetPostsPageResponse:
    properties:
      max_page_number:
        type: integer
      page_number:
        type: integer
      posts:
        items:
          $ref: '#/definitions/dto.Post'
        type: array
    type: object
  dto.GetStatsResponse:
    properties:
      start_interval:
        type: string
      stats:
        items:
          $ref: '#/definitions/dto.StatsDay'
        type: array
    type: object
  dto.IcePhenomenia:
    properties:
      intensity:
        type: integer
      phenomen:
        type: integer
    type: object
  dto.Post:
    properties:
      code:
        type: string
      id:
        type: string
      name:
        type: string
      river:
        type: string
    type: object
  dto.PostRequest:
    properties:
      post:
        $ref: '#/definitions/dto.Post'
    type: object
  dto.PostResponse:
    properties:
      post:
        $ref: '#/definitions/dto.Post'
    type: object
  dto.PostsResponse:
    properties:
      posts:
        items:
          $ref: '#/definitions/dto.Post'
        type: array
    type: object
  dto.RemoveControlValueRequest:
    properties:
      id:
        type: string
    type: object
  dto.RemoveControlValueResponse:
    properties:
      success:
        type: boolean
    type: object
  dto.StatsDay:
    properties:
      adverse:
        type: integer
      dangerous:
        type: integer
      date:
        type: string
      floodplain:
        type: integer
      norm:
        type: integer
      waterLevel:
        type: integer
    type: object
  dto.Telegram:
    properties:
      air_temperature:
        type: integer
      average_reservoir_level:
        type: integer
      datetime:
        type: string
      delta_water_level:
        type: integer
      downstream_level:
        type: integer
      group_id:
        type: string
      headwater_level:
        type: integer
      ice_height:
        type: integer
      ice_phenomenia_state:
        type: integer
      ice_phenomenias:
        items:
          $ref: '#/definitions/dto.IcePhenomenia'
        type: array
      id:
        type: string
      inflow:
        type: number
      is_dangerous:
        type: boolean
      post_code:
        type: string
      precipitation_duration:
        type: integer
      precipitation_value:
        type: number
      reservoir_date:
        type: string
      reservoir_volume:
        type: number
      reservoir_water_inflow_date:
        type: string
      reset:
        type: number
      snow_height:
        type: integer
      telegram_code:
        type: string
      water_flow:
        type: number
      water_level_on_time:
        type: integer
      water_level_on20h:
        type: integer
      water_temperature:
        type: number
    type: object
  dto.UpdateControlValueRequest:
    properties:
      control_values:
        items:
          $ref: '#/definitions/dto.ControlValue'
        type: array
    type: object
  dto.UpdateControlValueResponse:
    properties:
      control_values:
        items:
          $ref: '#/definitions/dto.ControlValue'
        type: array
    type: object
info:
  contact: {}
  description: This is the HLGateway server API.
  title: HLGateway API
  version: "1"
paths:
  /api/add-control-value:
    post:
      consumes:
      - application/json
      description: Add a new control value
      parameters:
      - description: Add Control Value Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.AddControlValueRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AddControlValueResponse'
      summary: Add control value
      tags:
      - Statistic
  /api/add-post:
    post:
      consumes:
      - application/json
      description: Add a new post
      parameters:
      - description: Add Post Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.PostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PostResponse'
      summary: Add post
      tags:
      - PostsService
  /api/add-telegram:
    post:
      consumes:
      - application/json
      description: Add a new telegram
      parameters:
      - description: Add Telegram Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.AddTelegramRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AddTelegramResponse'
      summary: Add telegram
      tags:
      - Buffer
  /api/check-water-level:
    get:
      consumes:
      - application/json
      description: Check Water Level
      parameters:
      - description: PostCode
        in: query
        name: postcode
        required: true
        type: string
      - description: date
        in: query
        name: date
        required: true
        type: string
      - description: WaterLevel
        in: query
        name: value
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CheckWaterLevelResponse'
      summary: Check Water Level
      tags:
      - Statistic
  /api/delete-post:
    delete:
      consumes:
      - application/json
      description: Delete the post by id
      parameters:
      - description: Delete Post Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.DeletePostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PostResponse'
      summary: Delete the post
      tags:
      - PostsService
  /api/find-posts:
    get:
      consumes:
      - application/json
      description: Find posts by serchstring
      parameters:
      - description: Search Substring
        in: query
        name: substring
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PostsResponse'
      summary: Find posts
      tags:
      - PostsService
  /api/get-all-posts:
    get:
      consumes:
      - application/json
      description: Get all posts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PostsResponse'
      summary: Get all posts
      tags:
      - PostsService
  /api/get-control-values:
    get:
      consumes:
      - application/json
      description: Get slice of control value with pages
      parameters:
      - description: PostCode
        in: query
        name: postcode
        required: true
        type: string
      - description: Type of control value
        in: query
        name: type
        required: true
        type: integer
      - description: Page
        in: query
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetControlValuesResponse'
      summary: Get control value
      tags:
      - Statistic
  /api/get-post:
    get:
      consumes:
      - application/json
      description: Get the post by id
      parameters:
      - description: Post ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PostResponse'
      summary: Get the post
      tags:
      - PostsService
  /api/get-posts:
    get:
      consumes:
      - application/json
      description: Get posts by page
      parameters:
      - description: Page number
        in: query
        name: page_number
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetPostsPageResponse'
      summary: Gets posts
      tags:
      - PostsService
  /api/get-stats:
    get:
      consumes:
      - application/json
      description: Get stats by day in time interval (for graph)
      parameters:
      - description: PostCode
        in: query
        name: postcode
        required: true
        type: string
      - description: Start Date
        in: query
        name: startdate
        required: true
        type: string
      - description: End Date
        in: query
        name: enddate
        required: true
        type: string
      - description: Graph Points
        in: query
        name: graphpoints
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetStatsResponse'
      summary: Get stats
      tags:
      - Statistic
  /api/remove-control-value:
    delete:
      consumes:
      - application/json
      description: Remove a control value by id
      parameters:
      - description: Remove Control Value Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RemoveControlValueRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RemoveControlValueResponse'
      summary: Remove control value
      tags:
      - Statistic
  /api/update-control-value:
    put:
      consumes:
      - application/json
      description: Update control value
      parameters:
      - description: Update Control Value Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateControlValueRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UpdateControlValueResponse'
      summary: Update control value
      tags:
      - Statistic
  /api/update-post:
    put:
      consumes:
      - application/json
      description: Update the post
      parameters:
      - description: Update Post Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.PostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PostResponse'
      summary: Update the post
      tags:
      - PostsService
swagger: "2.0"
